//
// GamePlatformMetacritic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GamePlatformMetacritic: Codable, JSONEncodable, Hashable {

    static let urlRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var metascore: Int?
    public var url: String?

    public init(metascore: Int? = nil, url: String? = nil) {
        self.metascore = metascore
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metascore
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(metascore, forKey: .metascore)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

