//
// GameStoreFull.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameStoreFull: Codable, JSONEncodable, Hashable {

    static let urlRule = StringRule(minLength: 1, maxLength: 500, pattern: nil)
    public var id: Int?
    public var gameId: String?
    public var storeId: String?
    public var url: String

    public init(id: Int? = nil, gameId: String? = nil, storeId: String? = nil, url: String) {
        self.id = id
        self.gameId = gameId
        self.storeId = storeId
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case gameId = "game_id"
        case storeId = "store_id"
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(gameId, forKey: .gameId)
        try container.encodeIfPresent(storeId, forKey: .storeId)
        try container.encode(url, forKey: .url)
    }
}

