//
// PersonSingle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PersonSingle: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let slugRule = StringRule(minLength: 1, maxLength: nil, pattern: "/^[-a-zA-Z0-9_]+$/")
    static let imageBackgroundRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let descriptionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: Int?
    public var name: String
    public var slug: String?
    public var image: String?
    public var imageBackground: String?
    public var description: String?
    public var gamesCount: Int?
    public var reviewsCount: Int?
    public var rating: Decimal?
    public var ratingTop: Int?
    public var updated: Date?

    public init(id: Int? = nil, name: String, slug: String? = nil, image: String? = nil, imageBackground: String? = nil, description: String? = nil, gamesCount: Int? = nil, reviewsCount: Int? = nil, rating: Decimal? = nil, ratingTop: Int? = nil, updated: Date? = nil) {
        self.id = id
        self.name = name
        self.slug = slug
        self.image = image
        self.imageBackground = imageBackground
        self.description = description
        self.gamesCount = gamesCount
        self.reviewsCount = reviewsCount
        self.rating = rating
        self.ratingTop = ratingTop
        self.updated = updated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case slug
        case image
        case imageBackground = "image_background"
        case description
        case gamesCount = "games_count"
        case reviewsCount = "reviews_count"
        case rating
        case ratingTop = "rating_top"
        case updated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(imageBackground, forKey: .imageBackground)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(gamesCount, forKey: .gamesCount)
        try container.encodeIfPresent(reviewsCount, forKey: .reviewsCount)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(ratingTop, forKey: .ratingTop)
        try container.encodeIfPresent(updated, forKey: .updated)
    }
}

