//
// StoreSingle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StoreSingle: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: 100, pattern: nil)
    static let domainRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    static let slugRule = StringRule(minLength: 1, maxLength: nil, pattern: "/^[-a-zA-Z0-9_]+$/")
    static let imageBackgroundRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: Int?
    public var name: String
    public var domain: String?
    public var slug: String?
    public var gamesCount: Int?
    public var imageBackground: String?
    public var description: String?

    public init(id: Int? = nil, name: String, domain: String? = nil, slug: String? = nil, gamesCount: Int? = nil, imageBackground: String? = nil, description: String? = nil) {
        self.id = id
        self.name = name
        self.domain = domain
        self.slug = slug
        self.gamesCount = gamesCount
        self.imageBackground = imageBackground
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case domain
        case slug
        case gamesCount = "games_count"
        case imageBackground = "image_background"
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(gamesCount, forKey: .gamesCount)
        try container.encodeIfPresent(imageBackground, forKey: .imageBackground)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

