//
// GamesList200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GamesList200Response: Codable, JSONEncodable, Hashable {

    public var count: Int
    public var next: String?
    public var previous: String?
    public var results: [Game]
    public var platforms: Bool?

    public init(count: Int, next: String? = nil, previous: String? = nil, results: [Game]) {
        self.count = count
        self.next = next
        self.previous = previous
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case next
        case previous
        case results
        case platforms = "user_platforms"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encodeIfPresent(next, forKey: .next)
        try container.encodeIfPresent(previous, forKey: .previous)
        try container.encode(results, forKey: .results)
        try container.encode(platforms, forKey: .platforms)
    }
}

