//
// GamePlatformsInnerRequirements.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GamePlatformsInnerRequirements: Codable, JSONEncodable, Hashable {

    public var minimum: String?
    public var recommended: String?

    public init(minimum: String? = nil, recommended: String? = nil) {
        self.minimum = minimum
        self.recommended = recommended
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case minimum
        case recommended
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(minimum, forKey: .minimum)
        try container.encodeIfPresent(recommended, forKey: .recommended)
    }
}

