//
// GamePlatformsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GamePlatformsInner: Codable, JSONEncodable, Hashable {

    public var platform: GamePlatformsInnerPlatform?
    public var releasedAt: String?
    public var requirements: GamePlatformsInnerRequirements?

    public init(platform: GamePlatformsInnerPlatform? = nil, releasedAt: String? = nil, requirements: GamePlatformsInnerRequirements? = nil) {
        self.platform = platform
        self.releasedAt = releasedAt
        self.requirements = requirements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
        case releasedAt = "released_at"
        case requirements
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(releasedAt, forKey: .releasedAt)
        try container.encodeIfPresent(requirements, forKey: .requirements)
    }
}

