//
// GameEsrbRating.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameEsrbRating: Codable, JSONEncodable, Hashable {

    public enum Slug: String, Codable, CaseIterable {
        case everyone = "everyone"
        case everyone10Plus = "everyone-10-plus"
        case teen = "teen"
        case mature = "mature"
        case adultsOnly = "adults-only"
        case ratingPending = "rating-pending"
    }
    public enum Name: String, Codable, CaseIterable {
        case everyone = "Everyone"
        case everyone10Plus = "Everyone 10+"
        case teen = "Teen"
        case mature = "Mature"
        case adultsOnly = "Adults Only"
        case ratingPending = "Rating Pending"
    }
    public var id: Int?
    public var slug: Slug?
    public var name: Name?

    public init(id: Int? = nil, slug: Slug? = nil, name: Name? = nil) {
        self.id = id
        self.slug = slug
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case slug
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

